### ISSUE TITLE
Extension does not work in VS Code 1.21

### ISSUE THREAD

**Issue by gabyx** [shd101wyy/vscode-markdown-preview-enhanced#81]
VSCode Version:
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Datum 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

When I run `Open Preview` it says `Running the contributed command:'markdown-preview-enhanced.openPreview' failed.`

JavaScript output shows:

```

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2844 [shd101wyy.markdown-preview-enhanced][UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
e.$onExtensionRuntimeError @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2844
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2844 Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:32:395
	at t.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:32:709)
	at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:34:483)
	at t.e.with (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:33:414)
	at Object.getPreviewUri (C:\Users\gabriel.nuetzi\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.3.3\out\src\preview-content-provider.js:464:30)
	at context.subscriptions.push.vscode.window.onDidChangeTextEditorSelection.event (C:\Users\gabriel.nuetzi\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.3.3\out\src\extension.js:320:59)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:992)
	at e.$acceptEditorPropertiesChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:667:458)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:587:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:587:550)
e.$onExtensionRuntimeError @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2844
```

**Comment by shd101wyy** [comment]
Hi @gabyx ,

I will investigate this error when I have time. Thank you for reporting it.

Thank you

**Comment by mneundorfer** [comment]
Experiencing the same(?) issue - maybe this helps in investigating: When trying to open the Preview via the context menu, nothing happens, when trying to open it via the keyboard shortcut, it get a `command 'markdown-preview-enhanced.openPreview' not found`

**Comment by gabyx** [comment]
I close this bug, as it was related to using an samba folder as Workspace in VS Code `\\Intranet\something`
which is bad anyways! Sorry for the inceonvenience!
